name: odomex
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.0
  flutter_riverpod: ^2.6.1
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  fl_chart: ^1.2.0
  package_info_plus: ^10.2.1
  url_launcher: ^6.3.2
  flutter_local_notifications: ^22.3.0
  timezone: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
